name: Deploy Lambda Function on push
on: push
jobs:
  build:
    name: Test action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: ./
        env:
          AWS_DEFAULT_REGION: "us-east-1"
          LAMBDA_FUNC_NAME: "pythonTestingSuiteNew"
          LAMBDA_RUNTIME: "python3.7"
          LAMBDA_HANDLER: "lambda_function.lambda_handler"
          LAMBDA_MEMORY: 128
          LAMBDA_TIMEOUT: 40
          BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
          AWS_SESSION_TOKEN: ${{ FQoGZXIvYXdzEJb//////////wEaDGiCxXHMjzxzk8X6VSKBAv3GEEQ+BA/rIHW8xR+aU6odiVD2dWj1dqcQQOQ0TUs53s71CJqCjB9OjJEdygYau0wGTk5N9zukK7TzUC3OSkfajifSmVxy6o6Ivoh+7k/3IJT/aXIvhy7j63Ik1VMCw9LizlScgsNzg5zYZ4kTH+wp5feB2ZVC5Euk5yVnI9Ts5QScFD57wBo26Klhm3pjPHWWQPc8HCV3ZLoIam3I6ylTUin12b7hVqcQNQi0R9JtaiYLeu4ubKbMQ2zKyEH0TPmRMUSRo7QA2pXq1jtpKwyvKbiBu6FsShMy1wz4bJUckZlcNQ81FHZzNPPEtDcIGP9j92bb36tNZ61n10YdTtAQKKu02+0F }}
          AWS_SECRET_ACCESS_KEY: ${{ +GxaoKJn8xAXpxotyigfFoilkJpTIDc2xNMmQ8Jw }}
          AWS_ACCESS_KEY_ID: ${{ ASIARPQ24FEQT3765HOI }}
